name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run cargo clippy
      run: cargo clippy

    - name: Run cargo fmt
      run: cargo fmt --check

    - name: Run cargo test
      run: cargo test --verbose

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose
  

